clc; clear;
T=(2*pi)/(120*pi);
a=0;
b=T;
x=0:0.02:1;
t=x.*b;
v_int=quad(voltage1(t),a,b);
v_rms=sqrt(v_int/b);
i_int=quad(current1(t),a,b);
i_rms=sqrt(i_int/b);
p_int=quad(inst_pr(t),a,b);
p_ave=p_int/b;
pf=p_ave/(i_rms*v_rms);
p_ave_an=(60/2)*cos(30*pi/180);
v_rms_an=10/sqrt(2);
pf_an=cos(30*pi/180);
fprintf('Average power, analytical: %f \n average power, numerical: %f\n', p_ave_an, p_ave);
fprintf('rms power, analytical: %f \n rms power, numerical: %f \n',p_ave_an, p_ave);
fprintf('Power vactor, analytical: %f \n power factor, numerical: %f \n',pf_an, pf);